### PR TITLE
Updates blazesym to 0.1.0rc1

### PR DESCRIPTION
**Pull request by sanchda**
# What does this PR do?

Seems like a prudent thing to do

# Motivation

Plus this upgrade happens when trying to cargo update, so why not?

### CODE REVIEW

**Review by morrisonlevi — APPROVED** [review]
I see no issue with an rc0 to rc1 update.

**Review by peterg17 — APPROVED** [review]
Upgrading the `blazesym-c` bindings to `0.1.0-rc.1` makes sense. I took a quick look at the new APIs and your changes check out

**Review by danielsn — APPROVED** [review]

**Comment by sanchda** [comment]
> Shouldn't [crashtracker blazesym version](https://github.com/DataDog/libdatadog/blob/main/crashtracker/Cargo.toml?rgh-link-date=2024-11-08T13%3A49%3A08Z#L28) be updated too ?

Yeah, I have a PR to consolidate these again.  I actually think this might have affected crashtracking unwinding on Alpine for some reason (glibc systems seem fine???)

**Comment by bwoebi** [comment]
@sanchda fwiw - there's also rc.2 by now, so if you update crashtracker blazesym, just update both too?

**Pull request merged**
