### PR TITLE
RFC: Allow verify trace-protobuf to continue on error

### PR DESCRIPTION
**Pull request by ivoanjo**
## What does this PR do?

This PR changes the "Verify trace-protobuf" github action to include "continue-on-error", so that unrelated PRs don't get marked as having failed CI when this action triggers.

Additionally, it makes use of the
`mainmatter/continue-on-error-comment@v1` action to turn these errors into a comment that gets added into the PR, so that we don't miss that this action failed -- we just make failures less noisy.

## Motivation:

I like having a green CI, and it's annoying to have a red CI because this action failed, since for many libdatadog PRs we don't care (e.g. this only impacts the serverless agent).

Thus, I decided to experiment with this alternative approach. As the PR title says -- comments welcome! Do you think this is reasonable?

## Additional Notes:

N/A

## How to test the change?

I'm hoping the action will start triggering for this PR itself, so we can see it running.

## For Reviewers
- [ ] If this PR touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.
- [x] This PR doesn't touch any of that.

### CODE REVIEW

**Review by paullegranddc — APPROVED** [review]

**Comment by paullegranddc** [comment]
It looks like the `Verify trace-protobuf` tests didn't run for this PR. Is this expected?

**Review by paullegranddc — CHANGES_REQUESTED** [review]
https://github.com/DataDog/libdatadog/actions/runs/6638247018

It looks like the action is invalid

**Comment by paullegranddc** [comment]
I added the action with the specific hash in this PR here https://github.com/DataDog/libdatadog/settings/actions

**Comment by ivoanjo** [comment]
Ahh, thanks for spotting that -- I had added with the `v1` tag and forgot that to make it match with the hash.

**Comment by ivoanjo** [comment]
It seems it has run now -- but doesn't output anything because it only runs on new PRs, not on branch updates ( https://github.com/DataDog/libdatadog/actions/runs/6642718147/job/18048114414?pr=275 ).

My suggestion is: Let's merge this in, and then right after I can open a tiny PR with a dummy fix to verify it's working fine. If it is, it stays, if not, I'll open a PR to revert it (or tweak it, if needed).

**Review by paullegranddc — APPROVED** [review]

**Comment by ivoanjo** [comment]
Update: Almost got it! https://github.com/DataDog/libdatadog/pull/280 has a tiny fix and otherwise this seems to work fine.

**Pull request merged**
