### PR TITLE
[profiling] Ensure shared library name has no soname set.

### PR DESCRIPTION
**Pull request by AlexJF**
# What does this PR do?

Ensure the libdatadog profiling shared library has no SONAME set in `.so` shared libraries.

# Motivation

In some environments, the libdatadog profiling shared library will include a SONAME and it will point to the library name previous to the rename in:

https://github.com/DataDog/libdatadog/blob/f5c7e888ee3aa6646986c90ed6917fe51c06a8c0/build-profiling-ffi.sh#L138

The existence of this SONAME makes it impossible to load libdatadog at runtime because the loading will be done based on the SONAME, not the actual library name:

```
2024-04-29_16:17:11.44159 W, [2024-04-29T16:17:11.441513 #43868]  WARN -- datadog: [datadog] Profiling was requested but is not supported, profiling disabled: There was an error loading the profiling native extension due to 'RuntimeError Failure to load datadog_profiling_native_extension.2.7.2_x86_64-linux due to libdatadog_profiling_ffi.so: cannot open shared object file: No such file or directory' at '/opt/dd-trace-rb/lib/datadog/profiling/load_native_extension.rb:41:in `<top (required)>''
```

# Additional Notes

We haven't been able to fully pinpoint what leads to different SONAME handling between different environments (e.g. my Ubuntu 24 LTS VM always includes them but not Ivo's Ubuntu 22 laptop) but we found the following places that show how "finicky" this can be:
* https://github.com/rust-lang/cargo/blob/d34d0a1e15b1005ed6ebddbe34aca2058e96293b/src/cargo/core/compiler/build_runner/compilation_files.rs#L691-L733
* https://github.com/lu-zero/cargo-c/blob/9c5c603f5b2b0d7c2228d13fe88ab631e0b195d4/src/target.rs#L76-L87 (I don't think we use this one but some similar code may be used somewhere in our build pipeline? 🤷‍♂️ )

# How to test the change?

Describe here in detail how the change can be validated.

## For Reviewers
- [ ] If this PR touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.
- [x] This PR doesn't touch any of that.

### CODE REVIEW

**Comment by r1viollet** [comment]
We talked about this. We are OK with removing the so name as we are not using it today. Would it be possible to just drop this within a cargo build script as part of the effort described in https://github.com/DataDog/libdatadog/issues/353

**Comment by r1viollet** [comment]
can it be part of the rust flags (like linker flags)? I think @gleocadie did work that is similar, we should put settings in a similar place.

**Comment by ivoanjo** [comment]
> can it be part of the rust flags (like linker flags)? I think @gleocadie did work that is similar, we should put settings in a similar place.

From what I chatted with @AlexJF, he did not find such an option, hence why he went with the "fix-after-the-fact" approach.

**Comment by ivoanjo** [comment]
I see some failures in our build pipeline

> ./build-profiling-ffi.sh: line 151: patchelf: command not found

We'll need a PR on that side to make sure our images have patchelf.

**Comment by ivoanjo** [comment]
PR to add `patchelf` to our centos build images: https://github.com/DataDog/libddprof-build/pull/40

**Comment by ivoanjo** [comment]
CI is now green for this one! @r1viollet thoughts on merging? Or do you want to hold on until we can see if there's a cleaner way to tell the rust compiler to not emit the soname at all?

**Comment by ivoanjo** [comment]
Actually CI isn't green lol, either I was looking at the wrong tab, or some of the jobs hadn't finished when I looked at it. Pardon the temporary insanity. Will look into the missing issue -- I think I didn't bump the CI image version thingy correctly.

**Comment by ivoanjo** [comment]
I'm moving this back to draft until we can pick it up again

**Comment by ivoanjo** [comment]
Closing as superceded by #628

**Pull request closed without merging**
