### PR TITLE
feat(profiling)!: send media type with files

### PR DESCRIPTION
**Pull request by morrisonlevi**
# What does this PR do?

Change the profiling `File` types to have a media type aka mime. This allows sending files like `metrics.json` with the right content type.

# Motivation

There was discussion on PR #81 and on Slack around the idea that it might be nicer for current users to send `metrics.json` in the `File` slice. However, there isn't support today for media types, which this fixes.

# Additional Notes

I like working with Grégory :)

# How to test the change?

All `File` objects now have a `mime` field which needs to be added. For encoded profiles, use type `mime::APPLICATION_OCTET_STREAM` or `"application/octet-stream"` as appropriate for which `File` type is being used.

### CODE REVIEW

**Comment by morrisonlevi** [comment]
I tried this out just now in the PHP profiler. I only sent the encoded profile (no metrics.json or anything), but profiles came in and seemed to work. If someone can test with `metrics.json` or code provenance or something and check the HTTP payload to have the right mimes, that would be where the value actually comes :)

**Comment by ivoanjo** [comment]
I'm a bit unsure about this being needed...

* Since libdatadog compresses all the files before sending, should we still send mimetypes that are not `application/octet-stream` even though the payload is compressed?
* Ruby has been sending `code-provenance.json` with libdatadog for quite a long time without this change. So I think it works without the mimetype... unless somehow the fallback support for Ruby that we had in the backend at some point is covering up an issue :thinking:

**Comment by morrisonlevi** [comment]
I forgot momentarily about compression. Is that going to screw up `metrics.json`? If so, then if you send certain mime types we can choose not to compress those.

**Comment by gleocadie** [comment]
> * Since libdatadog compresses all the files before sending, should we still send mimetypes that are not `application/octet-stream` even though the payload is compressed?

From what read here https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#:~:text=A%20multipart%20type%20is%20one,sent%20together%20in%20one%20transaction. for a `multipart`, each component can have its own mime type.

> I forgot momentarily about compression. Is that going to screw up metrics.json? If so, then if you send certain mime types we can choose not to compress those.

I do not think it will mess up the `metrics.json`. But I wonder if not adding the mime type won't screw up code that parse and read the HTTP request.

**Comment by ivoanjo** [comment]
> From what read here https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#:~:text=A%20multipart%20type%20is%20one,sent%20together%20in%20one%20transaction. for a multipart, each component can have its own mime type.

> I do not think it will mess up the metrics.json. But I wonder if not adding the mime type won't screw up code that parse and read the HTTP request.

My doubt here is, afaik libdatadog compresses each file individually, so technically every payload is an application/octet-stream, none of them go as text (other than `event.json`, which is not currently compressed):

https://github.com/DataDog/libdatadog/blob/a9725b920bec6cfe13d4bf1d29dab5105c3a892a/profiling/src/exporter/mod.rs#L227-L237

**Comment by gleocadie** [comment]
> > From what read here https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#:~:text=A%20multipart%20type%20is%20one,sent%20together%20in%20one%20transaction. for a multipart, each component can have its own mime type.
> 
> > I do not think it will mess up the metrics.json. But I wonder if not adding the mime type won't screw up code that parse and read the HTTP request.
> 
> My doubt here is, afaik libdatadog compresses each file individually, so technically every payload is an application/octet-stream, none of them go as text (other than `event.json`, which is not currently compressed):
> 
> https://github.com/DataDog/libdatadog/blob/a9725b920bec6cfe13d4bf1d29dab5105c3a892a/profiling/src/exporter/mod.rs#L227-L237

I see. Yeah 🤔 good point.

**Comment by morrisonlevi** [comment]
Intake doesn't care about the content-type of anything other than `event.json`. Closing out as unnecessary.

**Pull request closed without merging**
