### PR TITLE
Remove prost-build to use prost directly

### PR DESCRIPTION
**Pull request by morrisonlevi**
# What does this PR do?

Drops `prost-build` to use `prost` directly. Upgrades prost.

Pluralizes `function` to `functions`, `mapping` to `mappings`, etc.

Bumps versions to v0.9.1.

Fixes 3rdparty license file as I had to regenerate it anyway.

# Motivation

This is groundwork for implementing sample breakdowns, a part of the profiling timeline project. I've already implemented breakdowns once, but in a single PR it's a bit hard to review, so I'm breaking out this chunk.

Also, IDEs don't always handle generated files well, so getting rid of that makes onboarding a new person to the lib a bit easier.

# Additional Notes

We can revert the pluralization if people feel strongly, but I sometimes get tripped up when `mapping` is actually a `Vec<Mapping>`.

# How to test the change?

There are changes to pluralization if you were using the `datadog_profiling::profile::pprof` module directly, but otherwise nothing changes.

### CODE REVIEW

**Comment by morrisonlevi** [comment]
I'm not sure why the licenses are failing -- I regenerated them locally using the command in the gitlab job. Will have to dig through output. Maybe we accidentally committed a bad licenses file?

**Comment by pawelchcki** [comment]
> I'm not sure why the licenses are failing -- I regenerated them locally using the command in the gitlab job. Will have to dig through output. Maybe we accidentally committed a bad licenses file?

https://github.com/sstadick/cargo-bundle-licenses/releases
New version was released recently. I'd assume either CI one or your local one do not match

**Comment by morrisonlevi** [comment]
\o/

```diff
-    license: License specified in file (/tmp/dd-cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/LICENSE)
+    license: License specified in file ($CARGO_HOME/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/LICENSE)
```

**Review by pawelchcki — APPROVED** [review]

**Comment by pawelchcki** [comment]
Niice!
I wonder if this PR will speed up the builds and tests in CI :) (especially on Windows)

I'm willing to fire up my Windows laptop to test it

**Pull request merged**
